// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrsercqdxdouqvwbnwfy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impyc2VyY3FkeGRvdXF2d2Jud2Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MDg4NjUsImV4cCI6MjA2NDE4NDg2NX0.b0wl4NNgTuwIH8ZCqVyoHIug8peKQTneqHvz79-UYCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);