// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hspbqtqyjnmcxewlgeol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzcGJxdHF5am5tY3hld2xnZW9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MjMxODIsImV4cCI6MjA2NDI5OTE4Mn0.I0n70UZv6lupxytltUTN_nj_82QP1LWTSMN4nLkj-zI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);